" view
set termguicolors
set number
colorscheme desert
syntax on
set showmatch
set scrolloff=5
set ruler
set showcmd

" indent
set autoindent
set smarttab
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
